Explicit data prep calls in datamodule docs
Hi, 
if I don't call `dm.prepare_data()` and `dm.setup()` the datasets are not yet defined and thus I can't call to get the dataloaders (`dm.train_dataloaders()`). 
I get `AttributeError: 'MNISTDataModule' object has no attribute 'dataset_train'`. 
This should make it clearer, for people who want to simply copy&paste. 

In case I missed something never mind (weird thing is I can't quite find the call to setup() in the previous call to `trainer.fit()` either).